[08-03 09:38:51] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 09:38:51] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 09:38:52] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 09:38:53] [INFO] 连接成功，机器人开始运行
[08-03 09:38:53] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 09:39:34] [DEBUG] 心跳发送成功
[08-03 09:40:17] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 09:40:17] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 09:40:18] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 09:40:18] [INFO] 连接成功，机器人开始运行
[08-03 09:40:19] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 09:41:00] [DEBUG] 心跳发送成功
[08-03 09:41:41] [DEBUG] 心跳发送成功
[08-03 09:42:22] [DEBUG] 心跳发送成功
[08-03 09:43:04] [DEBUG] 心跳发送成功
[08-03 09:43:45] [DEBUG] 心跳发送成功
[08-03 09:44:26] [DEBUG] 心跳发送成功
[08-03 09:45:07] [DEBUG] 心跳发送成功
[08-03 09:45:49] [DEBUG] 心跳发送成功
[08-03 09:46:30] [DEBUG] 心跳发送成功
[08-03 09:47:11] [DEBUG] 心跳发送成功
[08-03 09:47:52] [DEBUG] 心跳发送成功
[08-03 09:48:37] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 09:48:37] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 09:48:37] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 09:48:38] [INFO] 连接成功，机器人开始运行
[08-03 09:48:38] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 09:48:51] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400893/threads/08b9bddfa6d983e6920b10fdfbaeb1023803488099b6b506)调用错误[500]，详情：{"code":503003,"message":"thread_id is invalid"}，trace_id：628f3b9659d461e3f9bb0d443d8ca1f0
[08-03 09:49:19] [DEBUG] 心跳发送成功
[08-03 09:50:00] [DEBUG] 心跳发送成功
[08-03 09:50:42] [DEBUG] 心跳发送成功
[08-03 09:51:23] [DEBUG] 心跳发送成功
[08-03 09:52:04] [DEBUG] 心跳发送成功
[08-03 09:52:46] [DEBUG] 心跳发送成功
[08-03 09:53:27] [DEBUG] 心跳发送成功
[08-03 09:54:08] [DEBUG] 心跳发送成功
[08-03 09:54:49] [DEBUG] 心跳发送成功
[08-03 09:55:31] [DEBUG] 心跳发送成功
[08-03 09:56:12] [DEBUG] 心跳发送成功
[08-03 09:56:53] [DEBUG] 心跳发送成功
[08-03 09:57:34] [DEBUG] 心跳发送成功
[08-03 09:58:16] [DEBUG] 心跳发送成功
[08-03 09:58:57] [DEBUG] 心跳发送成功
[08-03 09:59:38] [DEBUG] 心跳发送成功
[08-03 10:00:19] [DEBUG] 心跳发送成功
[08-03 10:01:01] [DEBUG] 心跳发送成功
[08-03 10:01:42] [DEBUG] 心跳发送成功
[08-03 10:02:23] [DEBUG] 心跳发送成功
[08-03 10:03:04] [DEBUG] 心跳发送成功
[08-03 10:03:46] [DEBUG] 心跳发送成功
[08-03 10:04:27] [DEBUG] 心跳发送成功
[08-03 10:05:30] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 10:05:30] [INFO] 重连成功，机器人继续运行
[08-03 10:06:17] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:06:17] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:06:18] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:06:18] [INFO] 连接成功，机器人开始运行
[08-03 10:06:19] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:06:36] [INFO] {"author": "{\"avatar\": \"http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711\", \"bot\": false, \"id\": \"7702932596097654633\", \"username\": \"\\u5e7d\\u7075\"}", "channel_id": "640400893", "content": "\u6b63\u6587", "guild_id": "803215361374150329", "id": "08b9bddfa6d983e6920b10fdfbaeb102380448a9a1b6b506", "member": "{\"joined_at\": \"2024-03-19T08:52:31+08:00\", \"nick\": \"\\u5e7d\\u7075\", \"roles\": [\"4\", \"18728375\", \"18761125\", \"20\"]}", "seq": 4, "seq_in_channel": "4", "timestamp": "2024-08-03T10:06:33+08:00", "t": "MESSAGE_CREATE", "event_id": "MESSAGE_CREATE:08b9bddfa6d983e6920b10fdfbaeb102380448a9a1b6b506", "treated_msg": "\u6b63\u6587", "api": "<qg_botsdk.api.API object at 0x0000027B2EF9F520>"}
[08-03 10:06:36] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400893/threads/08b9bddfa6d983e6920b10fdfbaeb102380448a9a1b6b506)调用错误[500]，详情：{"code":503003,"message":"thread_id is invalid"}，trace_id：5a5238a9e54b2a1de05b4aa2091e68e5
[08-03 10:06:36] [INFO] {"data": {"code": 503003, "message": "thread_id is invalid"}, "trace_id": "5a5238a9e54b2a1de05b4aa2091e68e5", "http_code": 500, "result": false}
[08-03 10:06:36] [ERROR] TypeError("wrap() got an unexpected keyword argument 'end'")
[08-03 10:06:36] [ERROR] [error:TypeError("wrap() got an unexpected keyword argument 'end'")] File "d:\code\qqbot0729\robot.py", line 133, in deliver
[08-03 10:07:00] [DEBUG] 心跳发送成功
[08-03 10:07:41] [DEBUG] 心跳发送成功
[08-03 10:08:22] [DEBUG] 心跳发送成功
[08-03 10:09:04] [DEBUG] 心跳发送成功
[08-03 10:09:45] [DEBUG] 心跳发送成功
[08-03 10:10:26] [DEBUG] 心跳发送成功
[08-03 10:11:08] [DEBUG] 心跳发送成功
[08-03 10:11:49] [DEBUG] 心跳发送成功
[08-03 10:12:30] [DEBUG] 心跳发送成功
[08-03 10:13:11] [DEBUG] 心跳发送成功
[08-03 10:13:52] [DEBUG] 心跳发送成功
[08-03 10:14:34] [DEBUG] 心跳发送成功
[08-03 10:19:29] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:19:29] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:19:29] [INFO] Session Manager结束中，正在保存数据...
[08-03 10:20:11] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:20:11] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:20:11] [INFO] 论坛事件订阅成功
[08-03 10:20:12] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:20:14] [INFO] 连接成功，机器人开始运行
[08-03 10:20:14] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:20:59] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:20:59] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:20:59] [INFO] 论坛事件订阅成功
[08-03 10:21:01] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:21:01] [INFO] 连接成功，机器人开始运行
[08-03 10:21:02] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:21:10] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}, {"elems": [{"text": {"text": "\n"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:21:07+08:00", "thread_id": "B_1394ad66591b0a001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_CREATE", "event_id": "FORUM_THREAD_CREATE:261489392_3df4beb0-e2c3-47c9-afa6-2a62bbb35337"}
[08-03 10:21:10] [INFO] {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}, {"elems": [{"text": {"text": "\n"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:21:07+08:00", "thread_id": "B_1394ad66591b0a001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}}
[08-03 10:21:10] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}, {"elems": [{"text": {"text": "\n"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:21:07+08:00", "thread_id": "B_1394ad66591b0a001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_UPDATE", "event_id": "FORUM_THREAD_UPDATE:0_dcec54db-80de-4040-ae48-260a979d0ab4"}
[08-03 10:21:10] [INFO] {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}, {"elems": [{"text": {"text": "\n"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:21:07+08:00", "thread_id": "B_1394ad66591b0a001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}}
[08-03 10:21:10] [INFO] {"author": "{\"avatar\": \"http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711\", \"bot\": false, \"id\": \"7702932596097654633\", \"username\": \"\\u5e7d\\u7075\"}", "channel_id": "640400893", "content": "\u6807\u9898", "guild_id": "803215361374150329", "id": "08b9bddfa6d983e6920b10fdfbaeb10238064893a8b6b506", "member": "{\"joined_at\": \"2024-03-19T08:52:31+08:00\", \"nick\": \"\\u5e7d\\u7075\", \"roles\": [\"4\", \"18728375\", \"18761125\", \"20\"]}", "seq": 6, "seq_in_channel": "6", "timestamp": "2024-08-03T10:21:07+08:00", "t": "MESSAGE_CREATE", "event_id": "MESSAGE_CREATE:08b9bddfa6d983e6920b10fdfbaeb10238064893a8b6b506", "treated_msg": "\u6807\u9898", "api": "<qg_botsdk.api.API object at 0x000001A7DCDEF520>"}
[08-03 10:21:10] [INFO] 回复消息共花费了：
[08-03 10:21:10] [INFO] 0:00:00.743135
[08-03 10:21:11] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}, {"elems": [{"text": {"text": "\n"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:21:07+08:00", "thread_id": "B_1394ad66591b0a001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_UPDATE", "event_id": "FORUM_THREAD_UPDATE:261489392_697f16ce-7970-493f-aa61-37be9da4febe"}
[08-03 10:21:11] [INFO] {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}, {"elems": [{"text": {"text": "\n"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:21:07+08:00", "thread_id": "B_1394ad66591b0a001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}}
[08-03 10:21:43] [DEBUG] 心跳发送成功
[08-03 10:22:31] [DEBUG] 心跳发送成功
[08-03 10:23:19] [DEBUG] 心跳发送成功
[08-03 10:23:46] [DEBUG] 心跳发送成功
[08-03 10:24:28] [DEBUG] 心跳发送成功
[08-03 10:25:09] [DEBUG] 心跳发送成功
[08-03 10:25:50] [DEBUG] 心跳发送成功
[08-03 10:26:18] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:26:18] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:26:18] [INFO] 论坛事件订阅成功
[08-03 10:26:18] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:26:19] [INFO] 连接成功，机器人开始运行
[08-03 10:26:19] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:26:29] [ERROR] NameError("name 'userbot' is not defined")
[08-03 10:26:29] [ERROR] [error:NameError("name 'userbot' is not defined")] File "d:\code\qqbot0729\robot.py", line 138, in forum_function
[08-03 10:26:29] [ERROR] NameError("name 'userbot' is not defined")
[08-03 10:26:29] [ERROR] [error:NameError("name 'userbot' is not defined")] File "d:\code\qqbot0729\robot.py", line 138, in forum_function
[08-03 10:26:29] [INFO] {"author": "{\"avatar\": \"http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711\", \"bot\": false, \"id\": \"7702932596097654633\", \"username\": \"\\u5e7d\\u7075\"}", "channel_id": "640400893", "content": "\u6807\u9898", "guild_id": "803215361374150329", "id": "08b9bddfa6d983e6920b10fdfbaeb102380748d3aab6b506", "member": "{\"joined_at\": \"2024-03-19T08:52:31+08:00\", \"nick\": \"\\u5e7d\\u7075\", \"roles\": [\"4\", \"18728375\", \"18761125\", \"20\"]}", "seq": 7, "seq_in_channel": "7", "timestamp": "2024-08-03T10:26:27+08:00", "t": "MESSAGE_CREATE", "event_id": "MESSAGE_CREATE:08b9bddfa6d983e6920b10fdfbaeb102380748d3aab6b506", "treated_msg": "\u6807\u9898", "api": "<qg_botsdk.api.API object at 0x00000189D842F550>"}
[08-03 10:26:29] [INFO] 回复消息共花费了：
[08-03 10:26:29] [INFO] 0:00:00.617868
[08-03 10:26:30] [ERROR] NameError("name 'userbot' is not defined")
[08-03 10:26:30] [ERROR] [error:NameError("name 'userbot' is not defined")] File "d:\code\qqbot0729\robot.py", line 138, in forum_function
[08-03 10:26:57] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:26:57] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:26:57] [INFO] 论坛事件订阅成功
[08-03 10:26:58] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:26:58] [INFO] 连接成功，机器人开始运行
[08-03 10:26:59] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:27:13] [INFO] 回复消息共花费了：
[08-03 10:27:13] [INFO] 0:00:00.819512
[08-03 10:27:38] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:27:38] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:27:38] [INFO] 论坛事件订阅成功
[08-03 10:27:38] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:27:39] [INFO] 连接成功，机器人开始运行
[08-03 10:27:39] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:27:47] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "eaa06ea29aa98e6373be32beb8b51041", "http_code": 200, "result": true}
[08-03 10:27:48] [INFO] 回复消息共花费了：
[08-03 10:27:48] [INFO] 0:00:00.657018
[08-03 10:27:48] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "13ba4e81eb5880ad91553204ce11f719", "http_code": 200, "result": true}
[08-03 10:27:49] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "cf2ba125f51dbf46a929f58854a9aee8", "http_code": 200, "result": true}
[08-03 10:28:20] [DEBUG] 心跳发送成功
[08-03 10:28:52] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:28:52] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:28:52] [INFO] 论坛事件订阅成功
[08-03 10:28:52] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:28:53] [INFO] 连接成功，机器人开始运行
[08-03 10:28:53] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:29:06] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "60220a437eb908d9e71e62bbd110e978", "http_code": 200, "result": true}
[08-03 10:29:06] [INFO] 回复消息共花费了：
[08-03 10:29:06] [INFO] 0:00:00.813907
[08-03 10:29:07] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "6a286b31700e94b890073436fe0fb7b7", "http_code": 200, "result": true}
[08-03 10:29:08] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "4d9e687765ce78d2ed16ee3a8a516e29", "http_code": 200, "result": true}
[08-03 10:29:34] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 10:29:35] [INFO] 重连成功，机器人继续运行
[08-03 10:30:07] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:30:07] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:30:07] [INFO] 论坛事件订阅成功
[08-03 10:30:07] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:30:08] [INFO] 连接成功，机器人开始运行
[08-03 10:30:08] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:30:25] [INFO] 回复消息共花费了：
[08-03 10:30:25] [INFO] 0:00:00.612420
[08-03 10:30:25] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "acb14d57076ad900d6422342766d1b65", "http_code": 200, "result": true}
[08-03 10:30:25] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "c304123458a61402a6e4991a0dca6327", "http_code": 200, "result": true}
[08-03 10:30:25] [INFO] {"data": {"user": {"id": "7702932596097654633", "username": "\u5e7d\u7075", "avatar": "http://thirdqq.qlogo.cn/g?b=oidb&k=kgPmib64Ge8qBDZ2rJf0ILg&kti=ZJv1DgAAAAE&s=0&t=1663121711", "bot": false, "union_openid": "D7E368CF8A8D0B0193590730A74D45AB", "union_user_account": ""}, "nick": "\u5e7d\u7075", "roles": ["4", "18728375", "18761125", "20"], "joined_at": "2024-03-19T08:52:31+08:00"}, "trace_id": "2f57e79a75c3c0dd2bbe84b5ae8d32fb", "http_code": 200, "result": true}
[08-03 10:30:49] [DEBUG] 心跳发送成功
[08-03 10:31:31] [DEBUG] 心跳发送成功
[08-03 10:32:12] [DEBUG] 心跳发送成功
[08-03 10:32:53] [DEBUG] 心跳发送成功
[08-03 10:33:02] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:33:02] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:33:02] [INFO] 论坛事件订阅成功
[08-03 10:33:03] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:33:04] [INFO] 连接成功，机器人开始运行
[08-03 10:33:04] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:33:45] [DEBUG] 心跳发送成功
[08-03 10:33:54] [INFO] 非正式成员发帖
[08-03 10:33:54] [INFO] 回复消息共花费了：
[08-03 10:33:54] [INFO] 0:00:00.400148
[08-03 10:33:54] [INFO] 非正式成员发帖
[08-03 10:33:55] [INFO] 非正式成员发帖
[08-03 10:34:26] [DEBUG] 心跳发送成功
[08-03 10:35:07] [DEBUG] 心跳发送成功
[08-03 10:35:49] [DEBUG] 心跳发送成功
[08-03 10:36:49] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 10:36:50] [INFO] 重连成功，机器人继续运行
[08-03 10:37:03] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:37:03] [INFO] 论坛事件订阅成功
[08-03 10:37:03] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:37:04] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:37:04] [INFO] 连接成功，机器人开始运行
[08-03 10:37:04] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:37:13] [INFO] 非正式成员发帖
[08-03 10:37:14] [INFO] 非正式成员发帖
[08-03 10:37:14] [INFO] 回复消息共花费了：
[08-03 10:37:14] [INFO] 0:00:00.556850
[08-03 10:37:15] [INFO] 非正式成员发帖
[08-03 10:37:37] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:37:37] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:37:37] [INFO] 论坛事件订阅成功
[08-03 10:37:37] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:37:38] [INFO] 连接成功，机器人开始运行
[08-03 10:37:38] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:37:44] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:37:42+08:00", "thread_id": "B_f697ad66a47104001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_CREATE", "event_id": "FORUM_THREAD_CREATE:261489392_cb2e9147-2a27-48fa-a641-0f234f6f650e"}
[08-03 10:37:45] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:37:42+08:00", "thread_id": "B_f697ad66a47104001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_UPDATE", "event_id": "FORUM_THREAD_UPDATE:0_4a3a0534-1748-42b8-8e28-92f3086fb9a4"}
[08-03 10:37:45] [INFO] 非正式成员发帖
[08-03 10:37:45] [INFO] 回复消息共花费了：
[08-03 10:37:45] [INFO] 0:00:00.743596
[08-03 10:37:45] [INFO] 非正式成员发帖
[08-03 10:37:46] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:37:42+08:00", "thread_id": "B_f697ad66a47104001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_UPDATE", "event_id": "FORUM_THREAD_UPDATE:261489392_d42e8872-e1bd-4ca9-9b1b-902df389c76e"}
[08-03 10:37:46] [INFO] 非正式成员发帖
[08-03 10:38:19] [DEBUG] 心跳发送成功
[08-03 10:39:01] [DEBUG] 心跳发送成功
[08-03 10:39:42] [DEBUG] 心跳发送成功
[08-03 10:40:23] [DEBUG] 心跳发送成功
[08-03 10:41:04] [DEBUG] 心跳发送成功
[08-03 10:41:36] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:41:36] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:41:36] [INFO] 论坛事件订阅成功
[08-03 10:41:36] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:41:37] [INFO] 连接成功，机器人开始运行
[08-03 10:41:37] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:41:44] [INFO] {"author_id": "7702932596097654633", "channel_id": "640400893", "guild_id": "803215361374150329", "thread_info": {"content": {"paragraphs": [{"elems": [{"text": {"text": "\u6807\u9898"}, "type": 1}], "props": {}}]}, "date_time": "2024-08-03T10:41:42+08:00", "thread_id": "B_e698ad66228001001441152192082765750X60", "title": {"paragraphs": [{"elems": [{"text": {"text": "\u6b63\u6587"}, "type": 1}], "props": {}}]}}, "t": "FORUM_THREAD_CREATE", "event_id": "FORUM_THREAD_CREATE:261489392_456fce97-7462-4fc6-ac37-1e8436a6d34a"}
[08-03 10:41:44] [INFO] 非正式成员发帖
[08-03 10:41:44] [INFO] 回复消息共花费了：
[08-03 10:41:44] [INFO] 0:00:00.570950
[08-03 10:42:18] [DEBUG] 心跳发送成功
[08-03 10:42:59] [DEBUG] 心跳发送成功
[08-03 10:44:00] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 10:44:00] [INFO] 重连成功，机器人继续运行
[08-03 10:44:08] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:44:08] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:44:08] [INFO] 论坛事件订阅成功
[08-03 10:44:08] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:44:09] [INFO] 连接成功，机器人开始运行
[08-03 10:44:09] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:44:45] [ERROR] ClientOSError(22, '信号灯超时时间已到', None, 121, None)
[08-03 10:44:45] [ERROR] [error:ClientOSError(22, '信号灯超时时间已到', None, 121, None)] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 622, in read
[08-03 10:44:50] [DEBUG] 心跳发送成功
[08-03 10:45:13] [INFO] 非正式成员发帖
[08-03 10:45:13] [ERROR] AttributeError("'event_class' object has no attribute 'thread_id'")
[08-03 10:45:13] [ERROR] [error:AttributeError("'event_class' object has no attribute 'thread_id'")] File "d:\code\qqbot0729\robot.py", line 145, in forum_function
[08-03 10:45:14] [INFO] 回复消息共花费了：
[08-03 10:45:14] [INFO] 0:00:00.321319
[08-03 10:45:32] [DEBUG] 心跳发送成功
[08-03 10:46:13] [DEBUG] 心跳发送成功
[08-03 10:46:31] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:46:31] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:46:31] [INFO] 论坛事件订阅成功
[08-03 10:46:32] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:46:33] [INFO] 连接成功，机器人开始运行
[08-03 10:46:33] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:46:42] [INFO] 非正式成员发帖
[08-03 10:46:42] [INFO] 已清除非法帖子
[08-03 10:46:42] [INFO] 回复消息共花费了：
[08-03 10:46:42] [INFO] 0:00:01.177493
[08-03 10:47:14] [DEBUG] 心跳发送成功
[08-03 10:47:55] [DEBUG] 心跳发送成功
[08-03 10:48:37] [DEBUG] 心跳发送成功
[08-03 10:49:18] [DEBUG] 心跳发送成功
[08-03 10:49:59] [DEBUG] 心跳发送成功
[08-03 10:50:40] [DEBUG] 心跳发送成功
[08-03 10:51:21] [DEBUG] 心跳发送成功
[08-03 10:52:22] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 10:52:22] [INFO] 重连成功，机器人继续运行
[08-03 10:53:04] [DEBUG] 心跳发送成功
[08-03 10:53:45] [DEBUG] 心跳发送成功
[08-03 10:54:20] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:54:20] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:54:20] [INFO] 论坛事件订阅成功
[08-03 10:54:20] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:54:21] [INFO] 连接成功，机器人开始运行
[08-03 10:54:21] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:54:27] [INFO] 非正式成员发帖
[08-03 10:54:27] [INFO] 回复消息共花费了：
[08-03 10:54:27] [INFO] 0:00:00.727788
[08-03 10:54:27] [INFO] 已清除非法帖子
[08-03 10:54:27] [WARNING] HTTP API(url:https://api.sgroup.qq.com/users/@me/dms)调用错误[500]，详情：{"code":305001,"message":"backend error"}，trace_id：84d61044f93ff042fb7a13da96c5d4cc
[08-03 10:54:27] [INFO] {"data": {"code": 305001, "message": "backend error"}, "trace_id": "84d61044f93ff042fb7a13da96c5d4cc", "http_code": 500, "result": false}
[08-03 10:54:56] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 10:54:56] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 10:54:56] [INFO] 论坛事件订阅成功
[08-03 10:54:57] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 10:54:57] [INFO] 连接成功，机器人开始运行
[08-03 10:54:58] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 10:55:01] [INFO] 非正式成员发帖
[08-03 10:55:02] [INFO] 回复消息共花费了：
[08-03 10:55:02] [INFO] 0:00:00.512260
[08-03 10:55:02] [INFO] 已清除非法帖子
[08-03 10:55:02] [INFO] {"data": {"guild_id": "9885869291104633758", "channel_id": "63080461722653701", "create_time": "1722653701"}, "trace_id": "ca3beaede3433d72ad32d2649d3137ea", "http_code": 200, "result": true}
[08-03 10:55:39] [DEBUG] 心跳发送成功
[08-03 10:56:20] [DEBUG] 心跳发送成功
[08-03 10:57:01] [DEBUG] 心跳发送成功
[08-03 10:57:42] [DEBUG] 心跳发送成功
[08-03 10:58:24] [DEBUG] 心跳发送成功
[08-03 10:59:05] [DEBUG] 心跳发送成功
[08-03 10:59:46] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 10:59:47] [INFO] 重连成功，机器人继续运行
[08-03 11:00:28] [DEBUG] 心跳发送成功
[08-03 11:01:10] [DEBUG] 心跳发送成功
[08-03 11:01:51] [DEBUG] 心跳发送成功
[08-03 11:02:32] [DEBUG] 心跳发送成功
[08-03 11:03:13] [DEBUG] 心跳发送成功
[08-03 11:04:14] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 11:04:17] [INFO] 重连成功，机器人继续运行
[08-03 11:04:59] [DEBUG] 心跳发送成功
[08-03 11:06:02] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:06:02] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:06:02] [INFO] 论坛事件订阅成功
[08-03 11:06:03] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:06:03] [INFO] 连接成功，机器人开始运行
[08-03 11:06:03] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:06:07] [INFO] 非正式成员发帖
[08-03 11:06:07] [INFO] 已清除非法帖子
[08-03 11:06:07] [INFO] 9885869291104633758
[08-03 11:06:07] [INFO] 回复消息共花费了：
[08-03 11:06:07] [INFO] 0:00:00.618175
[08-03 11:06:08] [WARNING] HTTP API(url:https://api.sgroup.qq.com/dms/9885869291104633758/messages)调用错误[400]，详情：{"code":304053,"message":"请求参数event_id无效","err_code":40034025,"trace_id":"e5bdb39cb4e5a71d03da3c3e233dcdd7"}，trace_id：e5bdb39cb4e5a71d03da3c3e233dcdd7
[08-03 11:06:08] [INFO] 已提醒成员先去考核区考核
[08-03 11:06:45] [DEBUG] 心跳发送成功
[08-03 11:07:26] [DEBUG] 心跳发送成功
[08-03 11:08:07] [DEBUG] 心跳发送成功
[08-03 11:08:54] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:08:54] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:08:54] [INFO] 论坛事件订阅成功
[08-03 11:08:55] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:08:55] [INFO] 连接成功，机器人开始运行
[08-03 11:08:55] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:08:59] [INFO] 非正式成员发帖
[08-03 11:09:00] [INFO] 已清除非法帖子
[08-03 11:09:00] [INFO] 回复消息共花费了：
[08-03 11:09:00] [INFO] 0:00:00.554916
[08-03 11:09:00] [INFO] 9885869291104633758
[08-03 11:09:00] [WARNING] HTTP API(url:https://api.sgroup.qq.com/dms/9885869291104633758/messages)调用错误[400]，详情：{"code":304053,"message":"请求参数event_id无效","err_code":40034025,"trace_id":"6ee68dc770b2b76cd43942d78c6b425b"}，trace_id：6ee68dc770b2b76cd43942d78c6b425b
[08-03 11:09:00] [INFO] 已提醒成员先去考核区考核
[08-03 11:09:13] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:09:13] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:09:13] [INFO] 论坛事件订阅成功
[08-03 11:09:13] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:09:14] [INFO] 连接成功，机器人开始运行
[08-03 11:09:14] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:09:22] [INFO] 非正式成员发帖
[08-03 11:09:22] [INFO] 回复消息共花费了：
[08-03 11:09:22] [INFO] 0:00:00.667231
[08-03 11:09:22] [INFO] 已清除非法帖子
[08-03 11:09:22] [INFO] 9885869291104633758
[08-03 11:09:22] [INFO] 已提醒成员先去考核区考核
[08-03 11:09:56] [DEBUG] 心跳发送成功
[08-03 11:10:37] [DEBUG] 心跳发送成功
[08-03 11:11:18] [DEBUG] 心跳发送成功
[08-03 11:11:59] [DEBUG] 心跳发送成功
[08-03 11:13:48] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:13:48] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:13:48] [INFO] 论坛事件订阅成功
[08-03 11:13:48] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:13:49] [INFO] 连接成功，机器人开始运行
[08-03 11:13:49] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:14:05] [INFO] 非正式成员发帖
[08-03 11:14:05] [INFO] 已清除非法帖子
[08-03 11:14:05] [INFO] 15314138914594751831
[08-03 11:14:06] [INFO] 回复消息共花费了：
[08-03 11:14:06] [INFO] 0:00:00.656721
[08-03 11:14:06] [WARNING] HTTP API(url:https://api.sgroup.qq.com/dms/15314138914594751831/messages)调用错误[400]，详情：{"code":304003,"message":"请求参数不允许包含url pd.qq.com","err_code":40034028,"trace_id":"dada6faf5b55b810271c52b6cddeb74a"}，trace_id：dada6faf5b55b810271c52b6cddeb74a
[08-03 11:14:06] [INFO] 已提醒成员先去考核区考核
[08-03 11:14:30] [DEBUG] 心跳发送成功
[08-03 11:15:11] [DEBUG] 心跳发送成功
[08-03 11:15:51] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:15:51] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:15:51] [INFO] 论坛事件订阅成功
[08-03 11:15:52] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:15:52] [INFO] 连接成功，机器人开始运行
[08-03 11:15:52] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:15:58] [INFO] 非正式成员发帖
[08-03 11:15:58] [INFO] 回复消息共花费了：
[08-03 11:15:58] [INFO] 0:00:00.409911
[08-03 11:15:58] [INFO] 已清除非法帖子
[08-03 11:15:59] [INFO] 15314138914594751831
[08-03 11:15:59] [INFO] 已提醒成员先去考核区考核
[08-03 11:16:34] [DEBUG] 心跳发送成功
[08-03 11:17:15] [DEBUG] 心跳发送成功
[08-03 11:17:56] [DEBUG] 心跳发送成功
[08-03 11:18:37] [DEBUG] 心跳发送成功
[08-03 11:19:19] [DEBUG] 心跳发送成功
[08-03 11:19:48] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:19:48] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:19:48] [INFO] 论坛事件订阅成功
[08-03 11:19:49] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:19:49] [INFO] 连接成功，机器人开始运行
[08-03 11:19:50] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:20:05] [INFO] 非正式成员particle发帖
[08-03 11:20:05] [INFO] 回复消息共花费了：
[08-03 11:20:05] [INFO] 0:00:00.657006
[08-03 11:20:05] [INFO] 已清除非法帖子
[08-03 11:20:05] [INFO] 已提醒成员先去考核区考核
[08-03 11:20:31] [DEBUG] 心跳发送成功
[08-03 11:20:54] [INFO] 机器人准备回复了
[08-03 11:20:57] [INFO] prompt_cache_hit_tokens=1216
[08-03 11:20:57] [INFO] prompt_cache_miss_tokens=39
[08-03 11:21:01] [INFO] prompt_cache_hit_tokens=1216
[08-03 11:21:01] [INFO] prompt_cache_miss_tokens=17
[08-03 11:21:01] [INFO] AI共花费了：
[08-03 11:21:01] [INFO] 0:00:07.065431
[08-03 11:21:01] [INFO] 回复消息共花费了：
[08-03 11:21:01] [INFO] 0:00:08.503080
[08-03 11:21:12] [DEBUG] 心跳发送成功
[08-03 11:21:53] [DEBUG] 心跳发送成功
[08-03 11:22:35] [DEBUG] 心跳发送成功
[08-03 11:22:40] [INFO] 机器人准备回复了
[08-03 11:22:47] [INFO] prompt_cache_hit_tokens=1408
[08-03 11:22:47] [INFO] prompt_cache_miss_tokens=19
[08-03 11:22:51] [INFO] prompt_cache_hit_tokens=1280
[08-03 11:22:51] [INFO] prompt_cache_miss_tokens=34
[08-03 11:22:51] [INFO] AI共花费了：
[08-03 11:22:51] [INFO] 0:00:10.434612
[08-03 11:22:51] [INFO]   幽灵成功通过考核
[08-03 11:22:52] [INFO] 回复消息共花费了：
[08-03 11:22:52] [INFO] 0:00:11.834941
[08-03 11:23:16] [DEBUG] 心跳发送成功
[08-03 11:24:16] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 11:24:17] [INFO] 重连成功，机器人继续运行
[08-03 11:24:39] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:24:39] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:24:39] [INFO] 论坛事件订阅成功
[08-03 11:24:40] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:24:40] [INFO] 连接成功，机器人开始运行
[08-03 11:24:41] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:24:48] [INFO] 机器人准备回复了
[08-03 11:24:56] [INFO] prompt_cache_hit_tokens=1408
[08-03 11:24:56] [INFO] prompt_cache_miss_tokens=19
[08-03 11:24:59] [INFO] prompt_cache_hit_tokens=1280
[08-03 11:24:59] [INFO] prompt_cache_miss_tokens=34
[08-03 11:24:59] [INFO] AI共花费了：
[08-03 11:24:59] [INFO] 0:00:10.854903
[08-03 11:24:59] [INFO]   幽灵成功通过考核
[08-03 11:25:00] [INFO] 回复消息共花费了：
[08-03 11:25:00] [INFO] 0:00:12.583503
[08-03 11:25:22] [DEBUG] 心跳发送成功
[08-03 11:26:03] [DEBUG] 心跳发送成功
[08-03 11:26:32] [INFO] 回复消息共花费了：
[08-03 11:26:32] [INFO] 0:00:00.585272
[08-03 11:26:44] [DEBUG] 心跳发送成功
[08-03 11:27:32] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:27:32] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:27:32] [INFO] 论坛事件订阅成功
[08-03 11:27:32] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:27:33] [INFO] 连接成功，机器人开始运行
[08-03 11:27:33] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:50:54] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:50:54] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:50:54] [INFO] 论坛事件订阅成功
[08-03 11:50:55] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:50:55] [INFO] 连接成功，机器人开始运行
[08-03 11:50:55] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:51:06] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 11:51:06] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 11:51:06] [INFO] 论坛事件订阅成功
[08-03 11:51:07] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 11:51:07] [INFO] 连接成功，机器人开始运行
[08-03 11:51:08] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 11:51:10] [INFO] 回复消息共花费了：
[08-03 11:51:10] [INFO] 0:00:00.510103
[08-03 11:51:10] [INFO] 回复消息共花费了：
[08-03 11:51:10] [INFO] 0:00:00.625665
[08-03 11:51:22] [INFO] 回复消息共花费了：
[08-03 11:51:22] [INFO] 0:00:00.398341
[08-03 11:51:49] [DEBUG] 心跳发送成功
[08-03 11:52:30] [DEBUG] 心跳发送成功
[08-03 11:53:11] [DEBUG] 心跳发送成功
[08-03 11:53:45] [INFO] 回复消息共花费了：
[08-03 11:53:45] [INFO] 0:00:01.017984
[08-03 11:53:53] [DEBUG] 心跳发送成功
[08-03 11:54:09] [INFO] 回复消息共花费了：
[08-03 11:54:09] [INFO] 0:00:00.685035
[08-03 11:54:34] [DEBUG] 心跳发送成功
[08-03 11:55:15] [DEBUG] 心跳发送成功
[08-03 11:55:56] [DEBUG] 心跳发送成功
[08-03 11:56:38] [DEBUG] 心跳发送成功
[08-03 11:57:19] [DEBUG] 心跳发送成功
[08-03 11:58:00] [DEBUG] 心跳发送成功
[08-03 11:58:42] [DEBUG] 心跳发送成功
[08-03 11:59:23] [DEBUG] 心跳发送成功
[08-03 12:00:04] [DEBUG] 心跳发送成功
[08-03 12:00:45] [DEBUG] 心跳发送成功
[08-03 12:01:26] [DEBUG] 心跳发送成功
[08-03 12:02:08] [DEBUG] 心跳发送成功
[08-03 13:49:54] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:49:54] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:49:54] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:49:54] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:49:57] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:49:57] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:49:57] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:00] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:00] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:00] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:03] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:03] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:03] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:06] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:06] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:06] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:09] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:09] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:09] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:12] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:12] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:12] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:15] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:15] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:15] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:18] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:18] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:18] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:21] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:21] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:21] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:24] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:24] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:24] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:27] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:27] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:27] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:30] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:30] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:30] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:33] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:33] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:33] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:36] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:36] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:36] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:39] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:39] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:39] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:42] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:42] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:42] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:45] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:45] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:45] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:48] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:48] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:48] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:51] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:51] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:51] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:54] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:54] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:54] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:50:57] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:50:57] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:50:57] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:00] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:00] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:00] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:03] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:03] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:03] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:06] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:06] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:06] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:09] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:09] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:09] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:12] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:12] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:12] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:15] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:15] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:15] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:18] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:18] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:18] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:21] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:21] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:21] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:24] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:24] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:24] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:27] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:27] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:27] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:30] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:30] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:30] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:33] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:33] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:33] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:36] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:36] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:36] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:39] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:39] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:39] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:42] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:42] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:42] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:45] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:45] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:45] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:48] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:48] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:48] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:51] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:51] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:51] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:54] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:54] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:54] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:51:57] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:51:57] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:51:57] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:52:00] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:52:00] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:52:00] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:52:03] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 13:52:03] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))
[08-03 13:52:03] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x0000023381C467C0>, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11004, 'getaddrinfo failed'))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[08-03 13:52:07] [INFO] 连接成功，机器人开始运行
[08-03 13:52:48] [DEBUG] 心跳发送成功
[08-03 13:53:29] [DEBUG] 心跳发送成功
[08-03 13:54:11] [DEBUG] 心跳发送成功
[08-03 13:54:52] [DEBUG] 心跳发送成功
[08-03 13:55:33] [DEBUG] 心跳发送成功
[08-03 13:56:14] [DEBUG] 心跳发送成功
[08-03 13:56:56] [DEBUG] 心跳发送成功
[08-03 13:57:37] [DEBUG] 心跳发送成功
[08-03 13:58:18] [DEBUG] 心跳发送成功
[08-03 13:58:59] [DEBUG] 心跳发送成功
[08-03 13:59:41] [DEBUG] 心跳发送成功
[08-03 14:08:44] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 14:08:47] [INFO] 重连成功，机器人继续运行
[08-03 14:09:29] [DEBUG] 心跳发送成功
[08-03 14:10:10] [DEBUG] 心跳发送成功
[08-03 14:10:51] [DEBUG] 心跳发送成功
[08-03 14:11:32] [DEBUG] 心跳发送成功
[08-03 14:12:14] [DEBUG] 心跳发送成功
[08-03 14:12:55] [DEBUG] 心跳发送成功
[08-03 14:13:36] [DEBUG] 心跳发送成功
[08-03 14:14:17] [DEBUG] 心跳发送成功
[08-03 14:14:59] [DEBUG] 心跳发送成功
[08-03 14:15:40] [DEBUG] 心跳发送成功
[08-03 14:16:21] [DEBUG] 心跳发送成功
[08-03 14:17:03] [DEBUG] 心跳发送成功
[08-03 14:17:44] [DEBUG] 心跳发送成功
[08-03 14:18:25] [DEBUG] 心跳发送成功
[08-03 14:19:06] [DEBUG] 心跳发送成功
[08-03 14:19:48] [DEBUG] 心跳发送成功
[08-03 14:20:29] [DEBUG] 心跳发送成功
[08-03 14:21:10] [DEBUG] 心跳发送成功
[08-03 14:21:51] [DEBUG] 心跳发送成功
[08-03 14:22:33] [DEBUG] 心跳发送成功
[08-03 14:35:07] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:35:07] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:35:07] [INFO] 论坛事件订阅成功
[08-03 14:35:08] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:35:08] [INFO] 连接成功，机器人开始运行
[08-03 14:35:09] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:35:27] [ERROR] TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")
[08-03 14:35:27] [ERROR] [error:TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")] File "d:\code\qqbot0729\robot.py", line 82, in deliver
[08-03 14:35:37] [ERROR] TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")
[08-03 14:35:37] [ERROR] [error:TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")] File "d:\code\qqbot0729\robot.py", line 82, in deliver
[08-03 14:35:48] [ERROR] TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")
[08-03 14:35:48] [ERROR] [error:TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")] File "d:\code\qqbot0729\robot.py", line 82, in deliver
[08-03 14:35:50] [DEBUG] 心跳发送成功
[08-03 14:36:03] [ERROR] TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")
[08-03 14:36:03] [ERROR] [error:TypeError("get_channels_info() missing 1 required positional argument: 'channel_id'")] File "d:\code\qqbot0729\robot.py", line 82, in deliver
[08-03 14:36:31] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:36:31] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:36:31] [INFO] 论坛事件订阅成功
[08-03 14:36:31] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:36:32] [INFO] 连接成功，机器人开始运行
[08-03 14:36:32] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:36:36] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/13004711861241069697)调用错误[400]，详情：{"message":"频道不存在","code":11263,"err_code":40022001,"trace_id":"371c17cfee6e16b451c3516043d848c8"}，trace_id：371c17cfee6e16b451c3516043d848c8
[08-03 14:36:36] [ERROR] TypeError("'Logger' object is not callable")
[08-03 14:36:36] [ERROR] [error:TypeError("'Logger' object is not callable")] File "d:\code\qqbot0729\robot.py", line 82, in deliver
[08-03 14:37:05] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:37:05] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:37:05] [INFO] 论坛事件订阅成功
[08-03 14:37:06] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:37:06] [INFO] 连接成功，机器人开始运行
[08-03 14:37:06] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:37:10] [ERROR] TypeError("'Logger' object is not callable")
[08-03 14:37:10] [ERROR] [error:TypeError("'Logger' object is not callable")] File "d:\code\qqbot0729\robot.py", line 82, in deliver
[08-03 14:37:22] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:37:22] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:37:22] [INFO] 论坛事件订阅成功
[08-03 14:37:23] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:37:23] [INFO] 连接成功，机器人开始运行
[08-03 14:37:23] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:38:05] [DEBUG] 心跳发送成功
[08-03 14:38:46] [DEBUG] 心跳发送成功
[08-03 14:38:56] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:38:56] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:38:56] [INFO] 论坛事件订阅成功
[08-03 14:38:56] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:38:57] [INFO] 连接成功，机器人开始运行
[08-03 14:38:57] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:39:35] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:39:35] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:39:35] [INFO] 论坛事件订阅成功
[08-03 14:39:36] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:39:36] [INFO] 连接成功，机器人开始运行
[08-03 14:39:36] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:40:17] [DEBUG] 心跳发送成功
[08-03 14:40:59] [DEBUG] 心跳发送成功
[08-03 14:41:40] [DEBUG] 心跳发送成功
[08-03 14:42:21] [DEBUG] 心跳发送成功
[08-03 14:43:03] [DEBUG] 心跳发送成功
[08-03 14:43:44] [DEBUG] 心跳发送成功
[08-03 14:44:25] [DEBUG] 心跳发送成功
[08-03 14:45:06] [DEBUG] 心跳发送成功
[08-03 14:56:10] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:56:10] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:56:10] [INFO] 论坛事件订阅成功
[08-03 14:56:11] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:56:12] [INFO] 连接成功，机器人开始运行
[08-03 14:56:12] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:56:53] [DEBUG] 心跳发送成功
[08-03 14:57:30] [INFO] 聯山.非法发帖
[08-03 14:57:30] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/655508173/threads/B_d6d4ad6694440c001441152188302364590X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：a2ada312964fa75d075a0171598f34f9
[08-03 14:57:30] [INFO] 已清除非法帖子
[08-03 14:57:30] [INFO] 已提醒成员
[08-03 14:57:34] [DEBUG] 心跳发送成功
[08-03 14:58:15] [DEBUG] 心跳发送成功
[08-03 14:58:38] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 14:58:38] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 14:58:38] [INFO] 论坛事件订阅成功
[08-03 14:58:39] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 14:58:39] [INFO] 连接成功，机器人开始运行
[08-03 14:58:39] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 14:59:17] [INFO] particle非法发帖
[08-03 14:59:17] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_42d5ad66b1d30d001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：266d6043e51377fe5992e6a7a338246e
[08-03 14:59:17] [INFO] 已清除非法帖子
[08-03 14:59:18] [WARNING] HTTP API(url:https://api.sgroup.qq.com/users/@me/dms)调用错误[500]，详情：{"code":305001,"message":"backend error"}，trace_id：6b3b1ff90252e9301d4fc67c7ad3d957
[08-03 14:59:18] [ERROR] AttributeError("'object_class' object has no attribute 'guild_id'")
[08-03 14:59:18] [ERROR] [error:AttributeError("'object_class' object has no attribute 'guild_id'")] File "d:\code\qqbot0729\robot.py", line 162, in forum_function
[08-03 14:59:21] [DEBUG] 心跳发送成功
[08-03 14:59:44] [INFO] 四年非法发帖
[08-03 14:59:44] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/655508173/threads/B_5dd5ad669e0804001441152192471618480X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：616abf88e788be51006e7e1f2cf62c31
[08-03 14:59:44] [INFO] 已清除非法帖子
[08-03 14:59:45] [INFO] 已提醒成员
[08-03 15:00:02] [DEBUG] 心跳发送成功
[08-03 15:00:43] [DEBUG] 心跳发送成功
[08-03 15:00:48] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 15:00:48] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 15:00:48] [INFO] 论坛事件订阅成功
[08-03 15:00:49] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 15:00:49] [INFO] 连接成功，机器人开始运行
[08-03 15:00:49] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 15:01:12] [INFO] particle非法发帖
[08-03 15:01:12] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_b5d5ad66ed1705001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：6521e4bdfde3918d7e9fa689d9cbc548
[08-03 15:01:12] [INFO] 已清除非法帖子
[08-03 15:01:13] [INFO] 已提醒成员
[08-03 15:01:31] [DEBUG] 心跳发送成功
[08-03 15:02:12] [DEBUG] 心跳发送成功
[08-03 15:02:53] [DEBUG] 心跳发送成功
[08-03 15:03:31] [INFO] 凉拌🙈非法发帖
[08-03 15:03:31] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/655508173/threads/B_40d6ad66291008001441152188693339960X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：ba4a1931fc98a8adff660f1729cc22b4
[08-03 15:03:31] [INFO] 已清除非法帖子
[08-03 15:03:32] [INFO] 已提醒成员
[08-03 15:03:34] [DEBUG] 心跳发送成功
[08-03 15:03:51] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 15:03:51] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 15:03:51] [INFO] 论坛事件订阅成功
[08-03 15:03:52] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 15:03:52] [INFO] 连接成功，机器人开始运行
[08-03 15:03:53] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 15:04:34] [DEBUG] 心跳发送成功
[08-03 15:05:15] [DEBUG] 心跳发送成功
[08-03 15:05:56] [DEBUG] 心跳发送成功
[08-03 15:06:37] [DEBUG] 心跳发送成功
[08-03 15:07:19] [DEBUG] 心跳发送成功
[08-03 15:08:00] [DEBUG] 心跳发送成功
[08-03 15:08:41] [DEBUG] 心跳发送成功
[08-03 15:09:23] [DEBUG] 心跳发送成功
[08-03 15:10:04] [DEBUG] 心跳发送成功
[08-03 15:10:45] [DEBUG] 心跳发送成功
[08-03 15:11:26] [DEBUG] 心跳发送成功
[08-03 15:11:53] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 15:11:53] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 15:11:53] [INFO] 论坛事件订阅成功
[08-03 15:11:54] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 15:11:54] [INFO] 连接成功，机器人开始运行
[08-03 15:11:55] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 15:12:10] [INFO] 640400892
[08-03 15:12:10] [INFO] 803215361374150329
[08-03 15:12:36] [DEBUG] 心跳发送成功
[08-03 15:12:53] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 15:12:53] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 15:12:53] [INFO] 论坛事件订阅成功
[08-03 15:12:54] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 15:12:54] [INFO] 连接成功，机器人开始运行
[08-03 15:12:55] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 15:13:01] [INFO] 640400892
[08-03 15:13:01] [INFO] 640400892
[08-03 15:13:01] [INFO] 正式成员发错地方了
[08-03 15:13:01] [INFO] particle非法发帖
[08-03 15:13:02] [INFO] 已清除非法帖子
[08-03 15:13:02] [INFO] 已提醒成员
[08-03 15:13:36] [DEBUG] 心跳发送成功
[08-03 15:14:17] [DEBUG] 心跳发送成功
[08-03 15:14:58] [DEBUG] 心跳发送成功
[08-03 15:15:40] [DEBUG] 心跳发送成功
[08-03 15:16:21] [DEBUG] 心跳发送成功
[08-03 15:17:02] [DEBUG] 心跳发送成功
[08-03 15:17:22] [INFO] 655513253
[08-03 15:17:22] [INFO] 655508173
[08-03 15:17:43] [DEBUG] 心跳发送成功
[08-03 15:18:24] [DEBUG] 心跳发送成功
[08-03 15:19:06] [DEBUG] 心跳发送成功
[08-03 15:19:47] [DEBUG] 心跳发送成功
[08-03 15:20:28] [DEBUG] 心跳发送成功
[08-03 15:21:10] [DEBUG] 心跳发送成功
[08-03 15:21:51] [DEBUG] 心跳发送成功
[08-03 15:22:32] [DEBUG] 心跳发送成功
[08-03 15:23:13] [DEBUG] 心跳发送成功
[08-03 15:23:54] [DEBUG] 心跳发送成功
[08-03 15:24:36] [DEBUG] 心跳发送成功
[08-03 15:25:17] [DEBUG] 心跳发送成功
[08-03 15:25:58] [DEBUG] 心跳发送成功
[08-03 15:26:40] [DEBUG] 心跳发送成功
[08-03 15:27:21] [DEBUG] 心跳发送成功
[08-03 15:28:02] [DEBUG] 心跳发送成功
[08-03 15:28:43] [DEBUG] 心跳发送成功
[08-03 15:29:25] [DEBUG] 心跳发送成功
[08-03 15:30:06] [DEBUG] 心跳发送成功
[08-03 15:30:47] [DEBUG] 心跳发送成功
[08-03 15:31:28] [DEBUG] 心跳发送成功
[08-03 15:32:10] [DEBUG] 心跳发送成功
[08-03 15:32:36] [INFO] 640400892
[08-03 15:32:36] [INFO] 640400892
[08-03 15:32:36] [INFO] 正式成员发错地方了
[08-03 15:32:36] [INFO] particle非法发帖
[08-03 15:32:37] [INFO] 已清除非法帖子
[08-03 15:32:37] [INFO] 已提醒成员
[08-03 15:32:51] [DEBUG] 心跳发送成功
[08-03 15:32:59] [INFO] 640400892
[08-03 15:32:59] [INFO] 640400892
[08-03 15:32:59] [INFO] 正式成员发错地方了
[08-03 15:32:59] [INFO] particle非法发帖
[08-03 15:33:00] [INFO] 已清除非法帖子
[08-03 15:33:00] [INFO] 已提醒成员
[08-03 15:33:32] [DEBUG] 心跳发送成功
[08-03 15:34:13] [DEBUG] 心跳发送成功
[08-03 15:34:55] [DEBUG] 心跳发送成功
[08-03 15:35:27] [INFO] 657944006
[08-03 15:35:27] [INFO] 640400892
[08-03 15:35:27] [INFO] 回复消息共花费了：
[08-03 15:35:27] [INFO] 0:00:00.422078
[08-03 15:35:36] [DEBUG] 心跳发送成功
[08-03 15:36:17] [DEBUG] 心跳发送成功
[08-03 15:36:45] [INFO] 655508173
[08-03 15:36:45] [INFO] 655508173
[08-03 15:36:45] [INFO] 正式成员发错地方了
[08-03 15:36:45] [INFO] 一只天降小麻雀非法发帖
[08-03 15:36:45] [INFO] 已清除非法帖子
[08-03 15:36:46] [INFO] 已提醒成员
[08-03 15:36:58] [DEBUG] 心跳发送成功
[08-03 15:37:40] [DEBUG] 心跳发送成功
[08-03 15:38:21] [DEBUG] 心跳发送成功
[08-03 15:39:02] [DEBUG] 心跳发送成功
[08-03 15:39:43] [DEBUG] 心跳发送成功
[08-03 15:40:25] [DEBUG] 心跳发送成功
[08-03 15:41:06] [DEBUG] 心跳发送成功
[08-03 15:41:28] [INFO] 655508173
[08-03 15:41:28] [INFO] 655508173
[08-03 15:41:28] [INFO] 正式成员发错地方了
[08-03 15:41:28] [INFO] 将走非法发帖
[08-03 15:41:28] [INFO] 已清除非法帖子
[08-03 15:41:29] [WARNING] HTTP API(url:https://api.sgroup.qq.com/dms/4013498001866804107/messages)调用错误[400]，详情：{"code":40034117,"message":"消息发送失败","err_code":40034117,"trace_id":"ebde20e2eb10a91359b811c9f9011ffd"}，trace_id：ebde20e2eb10a91359b811c9f9011ffd
[08-03 15:41:29] [INFO] 已提醒成员
[08-03 15:41:47] [DEBUG] 心跳发送成功
[08-03 15:42:28] [DEBUG] 心跳发送成功
[08-03 15:42:32] [INFO] 655513253
[08-03 15:42:32] [INFO] 655508173
[08-03 15:42:54] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 15:42:54] [INFO] 重连成功，机器人继续运行
[08-03 15:43:36] [DEBUG] 心跳发送成功
[08-03 15:44:17] [DEBUG] 心跳发送成功
[08-03 15:44:58] [DEBUG] 心跳发送成功
[08-03 15:45:40] [DEBUG] 心跳发送成功
[08-03 15:46:21] [DEBUG] 心跳发送成功
[08-03 15:47:02] [DEBUG] 心跳发送成功
[08-03 15:47:28] [INFO] 655513253
[08-03 15:47:28] [INFO] 655508173
[08-03 15:47:43] [DEBUG] 心跳发送成功
[08-03 15:48:03] [INFO] 655508173
[08-03 15:48:03] [INFO] 655508173
[08-03 15:48:03] [INFO] 正式成员发错地方了
[08-03 15:48:03] [INFO] 逍遥 の幻梦非法发帖
[08-03 15:48:03] [INFO] 已清除非法帖子
[08-03 15:48:03] [INFO] 已提醒成员
[08-03 15:48:06] [INFO] 655513253
[08-03 15:48:06] [INFO] 655508173
[08-03 15:48:25] [DEBUG] 心跳发送成功
[08-03 15:49:06] [DEBUG] 心跳发送成功
[08-03 15:49:29] [INFO] 655513253
[08-03 15:49:29] [INFO] 655508173
[08-03 15:49:47] [DEBUG] 心跳发送成功
[08-03 15:50:28] [DEBUG] 心跳发送成功
[08-03 15:51:10] [DEBUG] 心跳发送成功
[08-03 15:51:51] [DEBUG] 心跳发送成功
[08-03 15:52:32] [DEBUG] 心跳发送成功
[08-03 15:53:13] [DEBUG] 心跳发送成功
[08-03 15:53:39] [INFO] 655513253
[08-03 15:53:39] [INFO] 655508173
[08-03 15:53:55] [DEBUG] 心跳发送成功
[08-03 15:54:36] [DEBUG] 心跳发送成功
[08-03 15:55:17] [DEBUG] 心跳发送成功
[08-03 15:55:58] [DEBUG] 心跳发送成功
[08-03 15:55:59] [INFO] 655513253
[08-03 15:55:59] [INFO] 655508173
[08-03 15:56:40] [DEBUG] 心跳发送成功
[08-03 15:57:16] [INFO] 周远航非法发帖
[08-03 15:57:16] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/655508173/threads/B_d9e2ad66e72804001441152198317391880X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：8baba65167c4092d857aac8db6e94272
[08-03 15:57:16] [INFO] 已清除非法帖子
[08-03 15:57:16] [INFO] 已提醒成员
[08-03 15:57:21] [DEBUG] 心跳发送成功
[08-03 15:58:02] [DEBUG] 心跳发送成功
[08-03 15:58:43] [DEBUG] 心跳发送成功
[08-03 15:59:08] [INFO] 655508173
[08-03 15:59:08] [INFO] 655508173
[08-03 15:59:08] [INFO] 正式成员发错地方了
[08-03 15:59:08] [INFO] 将走非法发帖
[08-03 15:59:09] [INFO] 已清除非法帖子
[08-03 15:59:09] [INFO] 已提醒成员
[08-03 15:59:25] [DEBUG] 心跳发送成功
[08-03 16:00:06] [DEBUG] 心跳发送成功
[08-03 16:00:32] [INFO] 655508173
[08-03 16:00:32] [INFO] 655508173
[08-03 16:00:32] [INFO] 正式成员发错地方了
[08-03 16:00:32] [INFO] 将走非法发帖
[08-03 16:00:33] [INFO] 已清除非法帖子
[08-03 16:00:33] [INFO] 已提醒成员
[08-03 16:00:47] [DEBUG] 心跳发送成功
[08-03 16:01:28] [DEBUG] 心跳发送成功
[08-03 16:01:40] [INFO] 655513253
[08-03 16:01:40] [INFO] 655508173
[08-03 16:02:07] [INFO] 655513253
[08-03 16:02:07] [INFO] 655508173
[08-03 16:02:10] [DEBUG] 心跳发送成功
[08-03 16:02:17] [INFO] 655513253
[08-03 16:02:17] [INFO] 655508173
[08-03 16:02:37] [INFO] 机器人准备回复了
[08-03 16:02:38] [INFO] 回复消息共花费了：
[08-03 16:02:38] [INFO] 0:00:01.531331
[08-03 16:02:51] [DEBUG] 心跳发送成功
[08-03 16:03:10] [INFO] 机器人准备回复了
[08-03 16:03:11] [INFO] 回复消息共花费了：
[08-03 16:03:11] [INFO] 0:00:01.545486
[08-03 16:03:32] [DEBUG] 心跳发送成功
[08-03 16:04:13] [DEBUG] 心跳发送成功
[08-03 16:04:55] [DEBUG] 心跳发送成功
[08-03 16:05:36] [DEBUG] 心跳发送成功
[08-03 16:06:17] [DEBUG] 心跳发送成功
[08-03 16:06:59] [DEBUG] 心跳发送成功
[08-03 16:07:40] [DEBUG] 心跳发送成功
[08-03 16:08:21] [DEBUG] 心跳发送成功
[08-03 16:09:02] [DEBUG] 心跳发送成功
[08-03 16:09:44] [DEBUG] 心跳发送成功
[08-03 16:09:52] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 16:09:55] [INFO] 重连成功，机器人继续运行
[08-03 16:10:37] [DEBUG] 心跳发送成功
[08-03 19:11:40] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:11:40] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:11:40] [INFO] 论坛事件订阅成功
[08-03 19:11:41] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:11:41] [INFO] 连接成功，机器人开始运行
[08-03 19:11:42] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:13:44] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:13:44] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:13:44] [INFO] 论坛事件订阅成功
[08-03 19:13:44] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:13:45] [INFO] 连接成功，机器人开始运行
[08-03 19:13:45] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:14:26] [DEBUG] 心跳发送成功
[08-03 19:14:40] [INFO] 640400892
[08-03 19:14:40] [INFO] 640400892
[08-03 19:14:40] [INFO] 正式成员发错地方了
[08-03 19:14:40] [INFO] particle非法发帖
[08-03 19:14:41] [INFO] 已清除非法帖子
[08-03 19:14:41] [ERROR] TypeError("send_msg() got an unexpected keyword argument 'guild_id'")
[08-03 19:14:41] [ERROR] [error:TypeError("send_msg() got an unexpected keyword argument 'guild_id'")] File "d:\code\qqbot0729\robot.py", line 174, in forum_function
[08-03 19:15:07] [DEBUG] 心跳发送成功
[08-03 19:15:49] [DEBUG] 心跳发送成功
[08-03 19:15:51] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:15:51] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:15:51] [INFO] 论坛事件订阅成功
[08-03 19:15:52] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:15:53] [INFO] 连接成功，机器人开始运行
[08-03 19:15:53] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:16:34] [DEBUG] 心跳发送成功
[08-03 19:17:05] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:17:05] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:17:05] [INFO] 论坛事件订阅成功
[08-03 19:17:06] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:17:06] [INFO] 连接成功，机器人开始运行
[08-03 19:17:06] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:17:23] [INFO] 640400892
[08-03 19:17:23] [INFO] 640400892
[08-03 19:17:23] [INFO] 正式成员发错地方了
[08-03 19:17:23] [INFO] particle非法发帖
[08-03 19:17:24] [INFO] 已清除非法帖子
[08-03 19:17:25] [INFO] 已提醒成员
[08-03 19:17:48] [DEBUG] 心跳发送成功
[08-03 19:18:05] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:18:05] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:18:05] [INFO] 论坛事件订阅成功
[08-03 19:18:05] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:18:06] [INFO] 连接成功，机器人开始运行
[08-03 19:18:06] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:18:27] [INFO] 640400892
[08-03 19:18:27] [INFO] 640400892
[08-03 19:18:27] [INFO] 正式成员发错地方了
[08-03 19:18:27] [INFO] particle非法发帖
[08-03 19:18:28] [INFO] 已清除非法帖子
[08-03 19:18:28] [INFO] 已提醒成员
[08-03 19:18:47] [DEBUG] 心跳发送成功
[08-03 19:19:18] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:19:18] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:19:18] [INFO] 论坛事件订阅成功
[08-03 19:19:18] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:19:19] [INFO] 连接成功，机器人开始运行
[08-03 19:19:19] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:19:23] [INFO] 640400892
[08-03 19:19:23] [INFO] 640400892
[08-03 19:19:23] [INFO] 正式成员发错地方了
[08-03 19:19:23] [INFO] particle非法发帖
[08-03 19:19:23] [INFO] 已清除非法帖子
[08-03 19:19:24] [INFO] 已提醒成员
[08-03 19:20:00] [DEBUG] 心跳发送成功
[08-03 19:20:41] [DEBUG] 心跳发送成功
[08-03 19:20:47] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:20:47] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:20:47] [INFO] 论坛事件订阅成功
[08-03 19:20:47] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:20:48] [INFO] 连接成功，机器人开始运行
[08-03 19:20:48] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:21:00] [INFO] 正式成员发错地方了
[08-03 19:21:00] [INFO] particle非法发帖
[08-03 19:21:29] [DEBUG] 心跳发送成功
[08-03 19:22:11] [DEBUG] 心跳发送成功
[08-03 19:22:21] [INFO] 正式成员发错地方了
[08-03 19:22:21] [INFO] particle非法发帖
[08-03 19:22:52] [DEBUG] 心跳发送成功
[08-03 19:22:55] [INFO] 正式成员发错地方了
[08-03 19:22:55] [INFO] particle非法发帖
[08-03 19:23:33] [DEBUG] 心跳发送成功
[08-03 19:24:14] [DEBUG] 心跳发送成功
[08-03 19:24:56] [DEBUG] 心跳发送成功
[08-03 19:25:37] [DEBUG] 心跳发送成功
[08-03 19:26:18] [DEBUG] 心跳发送成功
[08-03 19:26:59] [DEBUG] 心跳发送成功
[08-03 19:27:41] [DEBUG] 心跳发送成功
[08-03 19:28:22] [DEBUG] 心跳发送成功
[08-03 19:29:03] [DEBUG] 心跳发送成功
[08-03 19:29:44] [DEBUG] 心跳发送成功
[08-03 19:30:26] [DEBUG] 心跳发送成功
[08-03 19:31:07] [DEBUG] 心跳发送成功
[08-03 19:31:48] [DEBUG] 心跳发送成功
[08-03 19:32:29] [DEBUG] 心跳发送成功
[08-03 19:32:55] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:32:55] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:32:55] [INFO] 论坛事件订阅成功
[08-03 19:32:55] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:32:56] [INFO] 连接成功，机器人开始运行
[08-03 19:32:56] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:33:37] [DEBUG] 心跳发送成功
[08-03 19:34:17] [INFO] particle非法发帖
[08-03 19:34:17] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_b615ae6615a306001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：f77f1c07156fffb14fd6954376fe623e
[08-03 19:34:17] [ERROR] AttributeError("'API' object has no attribute 'thr'")
[08-03 19:34:17] [ERROR] [error:AttributeError("'API' object has no attribute 'thr'")] File "d:\code\qqbot0729\robot.py", line 169, in forum_function
[08-03 19:34:18] [DEBUG] 心跳发送成功
[08-03 19:35:00] [DEBUG] 心跳发送成功
[08-03 19:35:13] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:35:13] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:35:13] [INFO] 论坛事件订阅成功
[08-03 19:35:13] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:35:13] [INFO] 连接成功，机器人开始运行
[08-03 19:35:14] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:35:55] [DEBUG] 心跳发送成功
[08-03 19:36:36] [DEBUG] 心跳发送成功
[08-03 19:37:06] [INFO] particle非法发帖
[08-03 19:37:07] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_5f16ae660cd80a001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：165d05cce6ee956420cac1958e47a57d
[08-03 19:37:17] [DEBUG] 心跳发送成功
[08-03 19:37:59] [DEBUG] 心跳发送成功
[08-03 19:38:40] [DEBUG] 心跳发送成功
[08-03 19:39:21] [DEBUG] 心跳发送成功
[08-03 19:40:02] [DEBUG] 心跳发送成功
[08-03 19:40:44] [DEBUG] 心跳发送成功
[08-03 19:41:25] [DEBUG] 心跳发送成功
[08-03 19:42:06] [DEBUG] 心跳发送成功
[08-03 19:42:47] [DEBUG] 心跳发送成功
[08-03 19:43:29] [DEBUG] 心跳发送成功
[08-03 19:44:10] [DEBUG] 心跳发送成功
[08-03 19:44:51] [DEBUG] 心跳发送成功
[08-03 19:45:32] [DEBUG] 心跳发送成功
[08-03 19:46:14] [WARNING] BOT_WS链接已断开，正在尝试重连……
[08-03 19:46:14] [INFO] 重连成功，机器人继续运行
[08-03 19:46:56] [DEBUG] 心跳发送成功
[08-03 19:47:37] [DEBUG] 心跳发送成功
[08-03 19:47:49] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:47:49] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:47:49] [INFO] 论坛事件订阅成功
[08-03 19:47:50] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:47:51] [INFO] 连接成功，机器人开始运行
[08-03 19:47:51] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:48:01] [INFO] particle非法发帖
[08-03 19:48:02] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_ee18ae66fab70b001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：cc12b3b557892b5ff32fda0cf214b13a
[08-03 19:48:40] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:48:40] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:48:40] [INFO] 论坛事件订阅成功
[08-03 19:48:41] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:48:41] [INFO] 连接成功，机器人开始运行
[08-03 19:48:41] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:48:52] [INFO] particle非法发帖
[08-03 19:48:52] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_2119ae66086906001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：f7de2fa3e7af0c36d836ea058ceb9e26
[08-03 19:48:52] [INFO] 已清除非法帖子
[08-03 19:48:53] [INFO] 已提醒成员
[08-03 19:49:15] [INFO] particle非法发帖
[08-03 19:49:15] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_3819ae6642ef00001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：ae9f561cd7fff1007373f26888627ebe
[08-03 19:49:15] [INFO] 已清除非法帖子
[08-03 19:49:15] [INFO] 已提醒成员
[08-03 19:49:22] [DEBUG] 心跳发送成功
[08-03 19:50:04] [DEBUG] 心跳发送成功
[08-03 19:50:45] [DEBUG] 心跳发送成功
[08-03 19:50:49] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:50:49] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:50:49] [INFO] 论坛事件订阅成功
[08-03 19:50:49] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:50:50] [INFO] 连接成功，机器人开始运行
[08-03 19:50:50] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:51:06] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_a719ae66a45106001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：7ec0d139a3e4ddf3488b8382be16f256
[08-03 19:51:31] [DEBUG] 心跳发送成功
[08-03 19:52:14] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 19:52:14] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 19:52:14] [INFO] 论坛事件订阅成功
[08-03 19:52:14] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 19:52:15] [INFO] 连接成功，机器人开始运行
[08-03 19:52:15] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 19:52:30] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_fb19ae66a91e02001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：fb47206dd5496942c27701b9d94a25ed
[08-03 19:52:57] [DEBUG] 心跳发送成功
[08-03 19:53:20] [ERROR] ClientOSError(22, '指定的网络名不再可用。', None, 64, None)
[08-03 19:53:21] [ERROR] [error:ClientOSError(22, '指定的网络名不再可用。', None, 64, None)] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 622, in read
[08-03 19:53:38] [DEBUG] 心跳发送成功
[08-03 19:53:56] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_511aae66da2805001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：e0fa3b29465d3774b1c90c61e922055c
[08-03 19:54:19] [DEBUG] 心跳发送成功
[08-03 19:55:00] [DEBUG] 心跳发送成功
[08-03 19:55:41] [DEBUG] 心跳发送成功
[08-03 19:56:23] [DEBUG] 心跳发送成功
[08-03 19:57:04] [DEBUG] 心跳发送成功
[08-03 19:57:45] [DEBUG] 心跳发送成功
[08-03 19:58:27] [DEBUG] 心跳发送成功
[08-03 19:59:08] [DEBUG] 心跳发送成功
[08-03 19:59:49] [DEBUG] 心跳发送成功
[08-03 19:59:55] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-8581685651402239484), ConnectionResetError(22, '指定的网络名不再可用。', None, 64, None))
[08-03 19:59:55] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-8581685651402239484), ConnectionResetError(22, '指定的网络名不再可用。', None, 64, None))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1000, in _wrap_create_connection
[08-03 20:00:02] [ERROR] ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-8581685651402239484), ConnectionResetError(22, '指定的网络名不再可用。', None, 64, None))
[08-03 20:00:02] [ERROR] [error:ClientConnectorError(ConnectionKey(host='api.sgroup.qq.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-8581685651402239484), ConnectionResetError(22, '指定的网络名不再可用。', None, 64, None))] File "C:\Users\particle\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1000, in _wrap_create_connection
[08-03 20:00:30] [DEBUG] 心跳发送成功
[08-03 20:01:12] [DEBUG] 心跳发送成功
[08-03 20:01:53] [DEBUG] 心跳发送成功
[08-03 20:02:05] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 20:02:05] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 20:02:05] [INFO] 论坛事件订阅成功
[08-03 20:02:05] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 20:02:06] [INFO] 连接成功，机器人开始运行
[08-03 20:02:06] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 20:02:44] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 20:02:44] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 20:02:44] [INFO] 论坛事件订阅成功
[08-03 20:02:44] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 20:02:44] [INFO] 连接成功，机器人开始运行
[08-03 20:02:45] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 20:02:50] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_671cae6678550b001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：c32ab4b42c9395bd2b11c731b99f0459
[08-03 20:03:26] [DEBUG] 心跳发送成功
[08-03 20:03:38] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 20:03:38] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 20:03:38] [INFO] 论坛事件订阅成功
[08-03 20:03:38] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 20:03:39] [INFO] 连接成功，机器人开始运行
[08-03 20:03:39] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 20:04:17] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 20:04:17] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 20:04:17] [INFO] 论坛事件订阅成功
[08-03 20:04:18] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 20:04:18] [INFO] 连接成功，机器人开始运行
[08-03 20:04:18] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 20:04:23] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_c41cae6617c403001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：aaa22cf1110fc1473d04c6f527dbab90
[08-03 20:04:24] [WARNING] Deprecated warning: 此发送方式即将废弃，请使用send_msg()并传入msg_model中的消息对象
[08-03 20:04:24] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/657968187/messages)调用错误[500]，详情：{"code":304005,"message":"reach embed size or field size limit,embed.fields limit","err_code":304005,"trace_id":"885a62667151e31c8970e442a1200fdc"}，trace_id：885a62667151e31c8970e442a1200fdc
[08-03 20:04:59] [DEBUG] 心跳发送成功
[08-03 20:05:41] [DEBUG] 心跳发送成功
[08-03 20:06:22] [DEBUG] 心跳发送成功
[08-03 20:07:03] [DEBUG] 心跳发送成功
[08-03 20:07:44] [DEBUG] 心跳发送成功
[08-03 20:08:26] [DEBUG] 心跳发送成功
[08-03 20:08:45] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 20:08:45] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 20:08:45] [INFO] 论坛事件订阅成功
[08-03 20:08:45] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 20:08:46] [INFO] 连接成功，机器人开始运行
[08-03 20:08:46] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 20:08:54] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_d31dae6687d202001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：624f6910b2249ea963f9a885e83663fc
[08-03 20:09:27] [DEBUG] 心跳发送成功
[08-03 20:11:06] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 20:11:06] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 20:11:06] [INFO] 论坛事件订阅成功
[08-03 20:11:06] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 20:11:07] [INFO] 连接成功，机器人开始运行
[08-03 20:11:07] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 20:11:14] [INFO] particle非法发帖
[08-03 20:11:14] [WARNING] HTTP API(url:https://api.sgroup.qq.com/channels/640400892/threads/B_5f1eae66c7470e001441152189347118930X60)调用错误[500]，详情：{"code":503013,"message":"服务器内部错误"}，trace_id：91f2dc6445cbb8a91ca06db7d6a4afaa
[08-03 21:01:56] [INFO] Session Manager 读取了 D:\code\qqbot0729\session_data 的数据
[08-03 21:01:56] [INFO] 消息（所有消息）接收函数订阅成功
[08-03 21:01:56] [INFO] 论坛事件订阅成功
[08-03 21:01:56] [DEBUG] [机器人ws地址] wss://api.sgroup.qq.com/websocket
[08-03 21:01:57] [INFO] 连接成功，机器人开始运行
[08-03 21:01:57] [INFO] 机器人频道用户ID：16339539897453438804
[08-03 21:02:13] [INFO] 回复消息共花费了：
[08-03 21:02:13] [INFO] 0:00:00.575103
[08-03 21:02:16] [INFO] AI共花费了：
[08-03 21:02:16] [INFO] 0:00:11.891016
[08-03 21:02:16] [INFO] 幽灵 成功通过考核
[08-03 21:02:16] [INFO] 回复消息共花费了：
[08-03 21:02:16] [INFO] 0:00:13.728249
